### ISSUE TITLE
Double @ logos around atsign on PyPI

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_python#153]
### Describe the bug

Since switching to light/dark logos on README.md this results in PyPI showing both.

### Steps to reproduce

1. First I browse to https://pypi.org/project/atsdk/
2. See double logo under Project description

### Expected behavior

PyPI only shows a single logo

### Screenshots

![image](https://github.com/atsign-foundation/at_python/assets/478926/d85108b6-bed5-4a52-87e2-9be4a3898bee)

**Comment by xavierchanth** [comment]
sln: https://stackoverflow.com/questions/75552648/github-darkmode-vs-lightmode-images-and-pypi
