### ISSUE TITLE
Split tests into those requiring an atSign and those that don't

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_python#25]
### Is your feature request related to a problem? Please describe.

#23 was opened due to Dependabot PR (such as #22) test failing due to lack of access to secrets.

### Describe the solution you'd like

Split tests into those that don't need an atSign (and the secrets to use an atSign), and those that do need an atSign.

Make tests that don't need an atSign mandatory, and skip tests that need secrets for Dependabot PRs.

### Describe alternatives you've considered

Use the virtual environment (VE) for testing rather than live atSigns since VE has test data keys that don't need to be kept secret.

### Additional context

See at_server and at_client_sdk for examples of using VE for functional tests.

**Comment by cpswan** [comment]
@shahumang19 do you have time to take this on?

**Comment by shahumang19** [comment]
> @shahumang19 do you have time to take this on?

@cpswan 
Sure I'll work on this
