### ISSUE TITLE
Make this repo ready to be featured on our org README

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_python#4]
@shahumang19 great work on getting things this far. Are you ready for this to become something that we point people at and start building our own solutions with?

You'll see on our other main repos we've implemented OpenSSF Scorecards, which means putting in place:

- [x] Branch protection (meaning that future changes will need a PR approved by somebody different from the author)
- [x] Dependency pinning (take a look at at_server to see how we generate a pinned `requirements.txt` using Poetry)
- [x] Dependabot automation for dependency updates (again at_server etc. shows the way)

**Comment by shahumang19** [comment]
I have completed all tasks and created a PR. Please review it.
